---
- name: Deploy scicalc python container
  hosts: local
  become: true
  vars:
    container_name: scicalc_py
  tasks:
    - name: Pull image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Remove old container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true
      ignore_errors: true

    - name: Run new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image }}"
        state: started
        detach: true
        restart_policy: unless-stopped
        command: tail -f /dev/null
